"""
README Builder for Controllable Image Generation Project

Generates the final README.md content with architecture diagrams,
results tables, visual grids, reproducibility instructions, and links.

Uses a structured builder pattern with Python f-strings to produce
the complete README content.

Requirements Addressed: 11.1, 11.2, 11.3, 11.4, 14.1, 14.2, 14.3,
                        15.1, 15.2, 15.3, 15.4, 15.5, 16.1, 16.2, 16.3
"""

import sys
from pathlib import Path
from typing import Optional

# Add project root to path for imports
_project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_project_root))

import importlib.util

_models_spec = importlib.util.spec_from_file_location(
    "src.app.models", _project_root / "src" / "app" / "models.py"
)
_models_module = importlib.util.module_from_spec(_models_spec)
_models_spec.loader.exec_module(_models_module)
PublishConfig = _models_module.PublishConfig


class ReadmeBuilder:
    """Builds the final README.md content for the GitHub repository.

    Generates a polished README with architecture diagrams, quantitative
    results tables, visual grids, reproducibility instructions, and links
    to all published artifacts.

    The build() method returns the full README content as a string.
    Sections are generated by private methods and assembled in order.

    Requirements Addressed: 11.1, 11.2, 11.3, 11.4, 14.1, 14.2, 14.3,
                            15.1, 15.2, 15.3, 15.4, 15.5, 16.1, 16.2, 16.3
    """

    def build(self, metrics: Optional[dict] = None, config: Optional[PublishConfig] = None) -> str:
        """Build the complete README.md content.

        Assembles all sections in the correct order:
        1. Header (title + description)
        2. Architecture diagrams
        3. Results table
        4. Visual grid
        5. Reproducibility
        6. Links
        7. Tech stack

        Args:
            metrics: Optional dictionary with evaluation metrics per
                condition type. Keys are condition types, values are
                dicts with 'fid_score' and 'alignment_score'.
            config: Optional PublishConfig for generating links and URLs.

        Returns:
            Complete README.md content as a string.
        """
        if metrics is None:
            metrics = {}
        if config is None:
            config = PublishConfig()

        sections = [
            self._header_section(),
            self._architecture_diagrams(),
            self._results_table(metrics),
            self._visual_grid_section(),
            self._reproducibility_section(),
            self._links_section(config),
            self._tech_stack_section(),
        ]

        return "\n".join(sections) + "\n"

    def _header_section(self) -> str:
        """Generate the README header with project title and description.

        The first line is a Markdown level-1 heading with the project title.
        The first non-empty line after the title is a plain-text description
        of at most 200 characters stating the project's capability and
        primary conditioning approach.

        Requirements Addressed: 16.1, 16.2, 16.3

        Returns:
            Header section string with title and description.
        """
        title = "# Controllable Image Generation with Fine-Grained Conditioning"
        description = (
            "Train and deploy ControlNet adapters for spatial conditioning "
            "(depth, pose, edge) on Stable Diffusion 1.5 with fine-grained control."
        )
        return f"{title}\n\n{description}"

    def _architecture_diagrams(self) -> str:
        """Generate ASCII architecture diagrams for inference and training.

        Produces two diagrams inside fenced code blocks:
        1. Inference pipeline: shows Text Encoder, SD1.5 UNet (frozen),
           ControlNet (trainable), Zero Convolution, Noise Scheduler (DDIM),
           Condition Map input, Text Prompt input, Generated Image output.
        2. Training pipeline: shows Raw Image -> Condition Extractor ->
           Condition Map -> ControlNet (trainable) + SD1.5 UNet (frozen)
           -> Diffusion Loss.

        All lines within code blocks are at most 80 characters.
        The architecture section is placed between the project description
        and the results section.

        Requirements Addressed: 11.1, 11.2, 11.3, 11.4

        Returns:
            Architecture diagrams section string.
        """
        inference_diagram = (
            "```\n"
            "Inference Pipeline\n"
            "==================\n"
            "\n"
            "  Text Prompt          Condition Map\n"
            "      |                     |\n"
            "      v                     v\n"
            "┌──────────────┐   ┌─────────────────────┐\n"
            "│ Text Encoder │   │  ControlNet         │\n"
            "└──────┬───────┘   │  (trainable)        │\n"
            "       |           └──────────┬──────────┘\n"
            "       |                      |\n"
            "       |           ┌──────────v──────────┐\n"
            "       |           │ Zero Convolution    │\n"
            "       |           └──────────┬──────────┘\n"
            "       |                      |\n"
            "       v                      v\n"
            "┌────────────────────────────────────────┐\n"
            "│        SD1.5 UNet (frozen)             │\n"
            "└───────────────────┬────────────────────┘\n"
            "                    |\n"
            "                    v\n"
            "       ┌────────────────────────┐\n"
            "       │ Noise Scheduler (DDIM) │\n"
            "       └───────────┬────────────┘\n"
            "                   |\n"
            "                   v\n"
            "          Generated Image\n"
            "```"
        )

        training_diagram = (
            "```\n"
            "Training Pipeline\n"
            "=================\n"
            "\n"
            "  Raw Image\n"
            "      |\n"
            "      v\n"
            "┌─────────────────────────────┐\n"
            "│  Condition Extractor        │\n"
            "│  (depth / pose / edge)      │\n"
            "└──────────────┬──────────────┘\n"
            "               |\n"
            "               v\n"
            "        Condition Map\n"
            "               |\n"
            "               v\n"
            "┌─────────────────────────────┐\n"
            "│  ControlNet (trainable)     │\n"
            "└──────────────┬──────────────┘\n"
            "               |\n"
            "               v\n"
            "┌─────────────────────────────┐\n"
            "│  SD1.5 UNet (frozen)        │\n"
            "└──────────────┬──────────────┘\n"
            "               |\n"
            "               v\n"
            "       Diffusion Loss\n"
            "```"
        )

        return (
            "\n## Architecture\n\n"
            "### Inference Pipeline\n\n"
            f"{inference_diagram}\n\n"
            "### Training Pipeline\n\n"
            f"{training_diagram}"
        )

    def _results_table(self, metrics: dict) -> str:
        """Generate the quantitative results table section.

        Produces a Markdown table with columns for Model/Condition Type,
        FID Score (lower is better), and Alignment Score (higher is better).
        Includes one row per condition type (depth, pose, edge) plus a
        Vanilla SD1.5 baseline row. Alignment scores are annotated with
        the metric name used for each condition type.

        Missing metrics are displayed as "N/A".

        Requirements Addressed: 12.1, 12.2, 12.3, 12.4

        Args:
            metrics: Dictionary with condition type keys mapping to dicts
                containing 'fid_score' and 'alignment_score' values.
                May also contain a 'baseline' key for Vanilla SD1.5 scores.

        Returns:
            Results table section string.
        """
        # Metric annotations per condition type
        alignment_annotations = {
            "depth": "Pearson correlation",
            "pose": "normalized keypoint distance",
            "edge": "SSIM",
        }

        header = (
            "| Model / Condition Type | FID Score ↓ | Alignment Score ↑ |\n"
            "|---|---|---|"
        )

        rows = []

        # Condition type rows
        for condition_type in ["depth", "pose", "edge"]:
            condition_metrics = metrics.get(condition_type, {})

            # FID score
            fid_score = condition_metrics.get("fid_score")
            fid_str = f"{fid_score:.1f}" if fid_score is not None else "N/A"

            # Alignment score with metric annotation
            alignment_score = condition_metrics.get("alignment_score")
            annotation = alignment_annotations[condition_type]
            if alignment_score is not None:
                alignment_str = f"{alignment_score:.3f} ({annotation})"
            else:
                alignment_str = f"N/A ({annotation})"

            label = f"ControlNet — {condition_type.capitalize()}"
            rows.append(f"| {label} | {fid_str} | {alignment_str} |")

        # Vanilla SD1.5 baseline row
        baseline_metrics = metrics.get("baseline", {})
        baseline_fid = baseline_metrics.get("fid_score")
        baseline_fid_str = f"{baseline_fid:.1f}" if baseline_fid is not None else "N/A"
        baseline_alignment = baseline_metrics.get("alignment_score")
        baseline_alignment_str = (
            f"{baseline_alignment:.3f}" if baseline_alignment is not None else "N/A"
        )
        rows.append(f"| Vanilla SD1.5 (no ControlNet) | {baseline_fid_str} | {baseline_alignment_str} |")

        # Footnote about metric direction
        footnote = (
            "\n> **↓** = lower is better (FID) &nbsp; | &nbsp; "
            "**↑** = higher is better (alignment scores)"
        )

        table_content = header + "\n" + "\n".join(rows)

        return f"\n## Results\n\n{table_content}\n{footnote}"

    def _visual_grid_section(self) -> str:
        """Generate the visual comparison grid section.

        Produces a 4-column Markdown image grid with columns:
        Input Image, Condition Map, Generated Result, Without ControlNet.
        Includes at least 2 rows per condition type (depth, pose, edge)
        for a minimum of 6 total rows. Rows are visually separated by
        condition type with sub-headings.

        Requirements Addressed: 13.1, 13.2, 13.3

        Returns:
            Visual grid section string.
        """
        grid_header = (
            "| Input Image | Condition Map | Generated Result "
            "| Without ControlNet |\n"
            "|---|---|---|---|"
        )

        sections = []

        for condition_type in ["depth", "pose", "edge"]:
            label = condition_type.capitalize()
            condition_header = f"#### {label} Conditioning"

            # Two example rows per condition type
            row1 = (
                f"| ![input](assets/grid/{condition_type}_input_1.png) "
                f"| ![condition](assets/grid/{condition_type}_cond_1.png) "
                f"| ![generated](assets/grid/{condition_type}_gen_1.png) "
                f"| ![baseline](assets/grid/{condition_type}_base_1.png) |"
            )
            row2 = (
                f"| ![input](assets/grid/{condition_type}_input_2.png) "
                f"| ![condition](assets/grid/{condition_type}_cond_2.png) "
                f"| ![generated](assets/grid/{condition_type}_gen_2.png) "
                f"| ![baseline](assets/grid/{condition_type}_base_2.png) |"
            )

            sections.append(
                f"{condition_header}\n\n{grid_header}\n{row1}\n{row2}"
            )

        grid_content = "\n\n".join(sections)

        return f"\n## Visual Examples\n\n{grid_content}"

    def _reproducibility_section(self) -> str:
        """Generate the reproducibility section with Colab instructions.

        Produces step-by-step shell commands for reproducing the full
        training and evaluation pipeline in Google Colab. Includes:
        - Sequential commands: clone, install, dataset, extract, train, evaluate
        - Hardware specification: T4 GPU with 15GB VRAM
        - Estimated training time per condition type
        - Verification steps for each stage

        Requirements Addressed: 14.1, 14.2, 14.3

        Returns:
            Reproducibility section string.
        """
        commands = (
            "```bash\n"
            "# 1. Clone the repository\n"
            "git clone https://github.com/deepradadiya/\\\n"
            "  Controllable-Image-Generation.git\n"
            "cd Controllable-Image-Generation\n"
            "\n"
            "# 2. Install dependencies\n"
            "pip install -r requirements.txt\n"
            "\n"
            "# 3. Download and prepare the dataset\n"
            "python scripts/download_dataset.py --output data/coco\n"
            "\n"
            "# 4. Extract condition maps\n"
            "python scripts/extract_conditions.py \\\n"
            "    --input data/coco \\\n"
            "    --output data/conditions \\\n"
            "    --types depth pose edge\n"
            "\n"
            "# 5. Train each adapter\n"
            "python scripts/train.py --condition depth \\\n"
            "    --output models/trained/depth\n"
            "python scripts/train.py --condition pose \\\n"
            "    --output models/trained/pose\n"
            "python scripts/train.py --condition edge \\\n"
            "    --output models/trained/edge\n"
            "\n"
            "# 6. Run evaluation\n"
            "python scripts/evaluate.py \\\n"
            "    --model-dir models/trained \\\n"
            "    --output evaluation/results\n"
            "```"
        )

        hardware = (
            "**Hardware Requirements:**\n"
            "- Google Colab T4 GPU (15 GB VRAM)\n"
            "- ~30 GB disk space for dataset and model weights\n"
            "\n"
            "**Estimated Training Time:**\n"
            "- ~4 hours per condition type on a T4 GPU\n"
            "- ~12 hours total for all three adapters (depth, pose, edge)"
        )

        verification = (
            "**Verification Steps:**\n"
            "1. After step 3: confirm `data/coco/` contains "
            "training images (`ls data/coco/train2017 | wc -l`)\n"
            "2. After step 4: confirm condition maps exist "
            "(`ls data/conditions/{depth,pose,edge}/ | head`)\n"
            "3. After step 5: confirm weight files exist "
            "(`ls models/trained/*/model.safetensors`)\n"
            "4. After step 6: confirm evaluation results "
            "(`cat evaluation/results/metrics.json`)"
        )

        return (
            "\n## How to Reproduce in Colab\n\n"
            f"{commands}\n\n"
            f"{hardware}\n\n"
            f"{verification}"
        )

    def _links_section(self, config: PublishConfig) -> str:
        """Generate the links section with URLs to all project artifacts.

        Produces clickable URLs to:
        - All 3 HuggingFace model repositories
        - HuggingFace Space demo
        - Weights & Biases training logs

        Requirements Addressed: 15.1, 15.2, 15.3

        Args:
            config: PublishConfig with hf_username, repo_prefix,
                and space_repo_name fields.

        Returns:
            Links section string.
        """
        base_url = "https://huggingface.co"
        username = config.hf_username
        prefix = config.repo_prefix
        space_name = config.space_repo_name

        depth_url = f"{base_url}/{username}/{prefix}-depth"
        pose_url = f"{base_url}/{username}/{prefix}-pose"
        edge_url = f"{base_url}/{username}/{prefix}-edge"
        space_url = f"{base_url}/spaces/{username}/{space_name}"
        wandb_url = (
            f"https://wandb.ai/{username}/controlnet-fine-grained-conditioning"
        )

        links = (
            f"| Artifact | Link |\n"
            f"|---|---|\n"
            f"| ControlNet — Depth | [{username}/{prefix}-depth]({depth_url}) |\n"
            f"| ControlNet — Pose | [{username}/{prefix}-pose]({pose_url}) |\n"
            f"| ControlNet — Edge | [{username}/{prefix}-edge]({edge_url}) |\n"
            f"| Live Demo (Space) | [{username}/{space_name}]({space_url}) |\n"
            f"| Training Logs (W&B) | [W&B Project]({wandb_url}) |"
        )

        return f"\n## Links\n\n{links}"

    def _tech_stack_section(self) -> str:
        """Generate the tech stack section and resume bullet point.

        Lists at least 5 frameworks/libraries used in the training and
        inference pipelines. Includes a resume bullet point suggestion
        referencing a quantitative metric.

        Requirements Addressed: 15.4, 15.5

        Returns:
            Tech stack section string with resume bullet point.
        """
        tech_stack = (
            "| Library | Purpose |\n"
            "|---|---|\n"
            "| [PyTorch](https://pytorch.org/) "
            "| Deep learning framework |\n"
            "| [Diffusers](https://huggingface.co/docs/diffusers) "
            "| Stable Diffusion & ControlNet pipelines |\n"
            "| [Gradio](https://gradio.app/) "
            "| Interactive web demo |\n"
            "| [Transformers](https://huggingface.co/docs/transformers) "
            "| Text encoder & model utilities |\n"
            "| [Weights & Biases](https://wandb.ai/) "
            "| Experiment tracking & logging |\n"
            "| [safetensors](https://github.com/huggingface/safetensors) "
            "| Safe model weight serialization |"
        )

        resume_bullet = (
            "**Resume Bullet Point:**\n\n"
            "> Trained and deployed three ControlNet adapters "
            "(depth, pose, edge) on Stable Diffusion 1.5, "
            "achieving FID score improvements over the vanilla baseline "
            "and alignment scores above 0.8 across all condition types."
        )

        return (
            f"\n## Tech Stack\n\n{tech_stack}\n\n"
            f"{resume_bullet}"
        )
